version: "3"    # specify what version of docker compose we wanna use
# if you want docker compose to spin you up a container you have to define a servie
services:
    api:
      build: .
      depends_on:
        - postgres  #tells docker to start the postgres container before the API container starts
      ports:
        - 8000:8000     # <port on localhost>:<port on container> 
      volumes:
        - ./:/home/mark/docker:ro  # it automatically syncs  the two folders - read only(container can't change any of these files)
      command: uvicorn ORM.main:app --host 0.0.0.0 --port 8000 --reload
      # env_file:
      #     - ./.env
      environment:
          - DATABASE_HOSTNAME=postgres
          - DATABASE_PORT=5432
          - DATABASE_PASSWORD=password123
          - DATABASE_NAME=FastAPI
          - DATABASE_USERNAME=postgres
          - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
          - ALGORITHM=HS256
          - ACCESS_TOKEN_EXPIRE_MINUTES=60

    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=password123
        - POSTGRES_DB=FastAPI
  
      volumes:
        - postgres-db:/var/lib/postgresql/data
    
volumes:
    postgres-db: